# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 210)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.kullanici_ad = QtWidgets.QLineEdit(self.widget)
        self.kullanici_ad.setObjectName("kullanici_ad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kullanici_ad)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.kullanici_soyad = QtWidgets.QLineEdit(self.widget)
        self.kullanici_soyad.setObjectName("kullanici_soyad")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kullanici_soyad)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.kullanici_yas = QtWidgets.QSpinBox(self.widget)
        self.kullanici_yas.setObjectName("kullanici_yas")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kullanici_yas)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.kullanici_meslek_combo_box = QtWidgets.QComboBox(self.widget)
        self.kullanici_meslek_combo_box.setObjectName("kullanici_meslek_combo_box")
        self.kullanici_meslek_combo_box.addItem("")
        self.kullanici_meslek_combo_box.addItem("")
        self.kullanici_meslek_combo_box.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kullanici_meslek_combo_box)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.kullanici_kaydet_button = QtWidgets.QPushButton(self.widget)
        self.kullanici_kaydet_button.setObjectName("kullanici_kaydet_button")
        self.horizontalLayout.addWidget(self.kullanici_kaydet_button)
        self.kullanici_web_sitesi = QtWidgets.QPushButton(self.widget)
        self.kullanici_web_sitesi.setObjectName("kullanici_web_sitesi")
        self.horizontalLayout.addWidget(self.kullanici_web_sitesi)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AD"))
        self.kullanici_ad.setPlaceholderText(_translate("MainWindow", "ADINIZ...."))
        self.label_2.setText(_translate("MainWindow", "SOYADINIZ"))
        self.kullanici_soyad.setPlaceholderText(_translate("MainWindow", "SOYADINIZ...."))
        self.label_3.setText(_translate("MainWindow", "YAŞ"))
        self.label_4.setText(_translate("MainWindow", "MESLEK"))
        self.kullanici_meslek_combo_box.setItemText(0, _translate("MainWindow", "MÜHENDİS"))
        self.kullanici_meslek_combo_box.setItemText(1, _translate("MainWindow", "ÖĞRENCİ"))
        self.kullanici_meslek_combo_box.setItemText(2, _translate("MainWindow", "İŞSİZ"))
        self.kullanici_kaydet_button.setText(_translate("MainWindow", "KAYDET"))
        self.kullanici_web_sitesi.setText(_translate("MainWindow", "WEBSİTESİ"))
